# Generated by Django 4.2.7 on 2025-10-01 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_outfitrecommendation_useroutfitpreference_outfititem'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='accessory_type',
            field=models.CharField(blank=True, choices=[('watch', 'Watch'), ('sneaker', 'Sneaker')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_accessory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
